### ISSUE TITLE
Can't resolve name when the dockerized app and dockerized dnsmasq on the same host

### ISSUE THREAD

**Issue by snakezzl** [4km3/docker-dnsmasq#14]
I have a dockerized dnsmasq runing on the localhost (ip is 192.168.10.53), i can resolve names correctly with that dnsmasq.

```
╭─ ➜  /root/dns-test (elk@55)
╰─ docker ps | grep dnsmasq
ee90b8e56363        andyshinn/dnsmasq:2.76                                   "dnsmasq -k --log-..."   About an hour ago   Up 11 minutes       0.0.0.0:53->53/tcp, 0.0.0.0:53->53/udp             jjt-dnsmasq
```

```
╭─ ➜  /root/dns-test (elk@55)
╰─ host mysql localhost
Using domain server:
Name: localhost
Address: ::1#53
Aliases:

mysql has address 192.168.10.75
```

I have a docker-compose.yml on the some host (ip is 192.168.10.53) like below:

```
version: "3"

services:
  ms-registry:
    image: ms-registry:1.0-SNAPSHOT
    restart: always
    ports:
      - 8761:8080
    dns: 192.168.10.53
```

After run `docker-compose up`, i enter the ms-registry container, but i can't resolve names correctly. But, if the containerized dnsmasq is running on the other host (eg. 192.168.10.55), i can resolve the name correctly.

So, what's the problem?
