### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by ain-soph** [4km3/docker-dnsmasq#46]
Are you considering to change the GitHub workflow from `on push` to scheduled every month or so to keep `dnsmasq` version updated?

**Comment by panchoh** [comment]
Definitely a good idea, and not just replacing but supplementing, since both workflows have merit.

We have pending giving this repo a push (both literally and figuratively), in the following month. We'll take your input into account, thanks for providing it!

While we are at it, is there any other feedback you want to give us? Feel free to comment right here or open another issue if you think it makes more sense.

At any rate, thanks a bunch for the heads up!

**Comment by ain-soph** [comment]
> While we are at it, is there any other feedback you want to give us?

Wanna share my compose file which might help other easier to hand on:
```yaml
services:
  dnsmasq:
    image: 4km3/dnsmasq
    build: .
    container_name: dnsmasq
    # network_mode: host
    networks:
      - ipv6
    privileged: true
    user: 501:20  # Mac user group for easily editing logs outside
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq.log:/log/dnsmasq.log
    ports:
      - 53:53
      - 53:53/udp
    restart: unless-stopped
networks:
  ipv6:
    external: true
```
This could have logging by adding this option `log-facility=/log/dnsmasq.log` in the `dnsmasq.conf`

To run,
```docker network create --ipv6 ipv6```
```docker compose up --build -d```
